### ISSUE TITLE
Dynamically generate example values based on data.tweasel.org

### ISSUE THREAD

**Issue by baltpeter** [tweaselORG/tracker-wiki#15]
Now that data.tweasel.org is live, we can generate the example values based on that instead of using the static method I implemented in #3.

This can be based on the `debug-adapters` script in TrackHAR.

**Comment by zner0L** [comment]
Do we want to do that at compile- or at runtime?

**Comment by baltpeter** [comment]
Compile time. At runtime would be too resource-intensive and take too long.
